import Header from "@/components/header/Header";
import "./globals.css";
import "./fonts/font.css";
import Footer from "@/components/footer/Footer";
import Provider from "./context/Provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <Provider>

        <body
        className="bg-[#e1e1e1] yekanbakhReg"
        >
          <Header/>
          <div className=" min-w-screen max-w-screen overflow-x-hidden py-5 ">
        
              {children} 
          </div>
          <Footer/>
        </body>
      </Provider>

    </html>
  );
}
